#!/bin/sh
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf 0

cp -r 0.org 0

paraFoam -touch

runApplication blockMesh

application=`getApplication`

runApplication $application


# ----------------------------------------------------------------- end-of-file
