#!/bin/sh
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf 0

cp -r 0.org 0

paraFoam -touch

runApplication blockMesh
runApplication decomposePar -force

application=`getApplication`


runParallel $application

runApplication reconstructParMesh -newTimes

runApplication reconstructPar


# ----------------------------------------------------------------- end-of-file
